
api:
  image: reactioncommerce/reaction-api-base:latest
  ports:
    - 3000:3000
  links:
    - mongo
  environment:
    MONGO_URL: "mongodb://mongo:27017/api"

mongo:
  image: mongo:latest
  ports:
    - 27017:27017  
  command: mongod --storageEngine=wiredTiger
