version: '3'

services:
  api:
    build:
      context: .
      args:
        NODE_ENV: "development"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/api"
    ports:
      - 3000:3000
    volumes:
      - api-yarn:/home/node/.cache/yarn
      - .:/opt/src

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    ports:
      - 27017:27017

volumes:
  api-yarn:
